[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  DATABASE_URL = "file:/opt/build/repo/prisma/dev.db"
  PRISMA_QUERY_ENGINE_TYPE = "library"

[[plugins]]
  package = "@netlify/plugin-nextjs"